otitle: Isha Shah
logo: "/images/is_headshot.jpeg?raw=true" 
description: > 
  Hi! I'm Isha Shah, currently a quantitative public policy researcher, project coordinator, and question-asker. I work for The Brookings Institution and Columbia University. On the right you'll find my current projects.
  <br><br>
  I studied neuroscience and economics at Barnard College. I like talking to strangers, reading too many news articles, and trying to make sense of the world through pseudoscientific doodles.
  <br><br>
  <a href="https://www.linkedin.com/in/ishashah27/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-155380510-1
